/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.squad.friend.model;
@org.apache.avro.specific.AvroGenerated
public enum FriendEventType implements org.apache.avro.generic.GenericEnumSymbol<FriendEventType> {
  FRIEND_ADDED, FRIEND_REMOVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FriendEventType\",\"namespace\":\"com.squad.friend.model\",\"symbols\":[\"FRIEND_ADDED\",\"FRIEND_REMOVE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
