/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.squad.friend.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Friend extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1959843805067148127L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Friend\",\"namespace\":\"com.squad.friend.model\",\"fields\":[{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"friendId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Friend> ENCODER =
      new BinaryMessageEncoder<Friend>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Friend> DECODER =
      new BinaryMessageDecoder<Friend>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Friend> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Friend> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Friend> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Friend>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Friend to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Friend from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Friend instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Friend fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String userId;
  @Deprecated public java.lang.String friendId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Friend() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param friendId The new value for friendId
   */
  public Friend(java.lang.String userId, java.lang.String friendId) {
    this.userId = userId;
    this.friendId = friendId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return friendId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.String)value$; break;
    case 1: friendId = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'friendId' field.
   * @return The value of the 'friendId' field.
   */
  public java.lang.String getFriendId() {
    return friendId;
  }


  /**
   * Sets the value of the 'friendId' field.
   * @param value the value to set.
   */
  public void setFriendId(java.lang.String value) {
    this.friendId = value;
  }

  /**
   * Creates a new Friend RecordBuilder.
   * @return A new Friend RecordBuilder
   */
  public static com.squad.friend.model.Friend.Builder newBuilder() {
    return new com.squad.friend.model.Friend.Builder();
  }

  /**
   * Creates a new Friend RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Friend RecordBuilder
   */
  public static com.squad.friend.model.Friend.Builder newBuilder(com.squad.friend.model.Friend.Builder other) {
    if (other == null) {
      return new com.squad.friend.model.Friend.Builder();
    } else {
      return new com.squad.friend.model.Friend.Builder(other);
    }
  }

  /**
   * Creates a new Friend RecordBuilder by copying an existing Friend instance.
   * @param other The existing instance to copy.
   * @return A new Friend RecordBuilder
   */
  public static com.squad.friend.model.Friend.Builder newBuilder(com.squad.friend.model.Friend other) {
    if (other == null) {
      return new com.squad.friend.model.Friend.Builder();
    } else {
      return new com.squad.friend.model.Friend.Builder(other);
    }
  }

  /**
   * RecordBuilder for Friend instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Friend>
    implements org.apache.avro.data.RecordBuilder<Friend> {

    private java.lang.String userId;
    private java.lang.String friendId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.squad.friend.model.Friend.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.friendId)) {
        this.friendId = data().deepCopy(fields()[1].schema(), other.friendId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Friend instance
     * @param other The existing instance to copy.
     */
    private Builder(com.squad.friend.model.Friend other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.friendId)) {
        this.friendId = data().deepCopy(fields()[1].schema(), other.friendId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.squad.friend.model.Friend.Builder setUserId(java.lang.String value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.squad.friend.model.Friend.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'friendId' field.
      * @return The value.
      */
    public java.lang.String getFriendId() {
      return friendId;
    }


    /**
      * Sets the value of the 'friendId' field.
      * @param value The value of 'friendId'.
      * @return This builder.
      */
    public com.squad.friend.model.Friend.Builder setFriendId(java.lang.String value) {
      validate(fields()[1], value);
      this.friendId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'friendId' field has been set.
      * @return True if the 'friendId' field has been set, false otherwise.
      */
    public boolean hasFriendId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'friendId' field.
      * @return This builder.
      */
    public com.squad.friend.model.Friend.Builder clearFriendId() {
      friendId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Friend build() {
      try {
        Friend record = new Friend();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.String) defaultValue(fields()[0]);
        record.friendId = fieldSetFlags()[1] ? this.friendId : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Friend>
    WRITER$ = (org.apache.avro.io.DatumWriter<Friend>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Friend>
    READER$ = (org.apache.avro.io.DatumReader<Friend>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userId);

    out.writeString(this.friendId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readString();

      this.friendId = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readString();
          break;

        case 1:
          this.friendId = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










