/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.squad.notebook.model;

@org.apache.avro.specific.AvroGenerated
public enum NoteEventType implements org.apache.avro.generic.GenericEnumSymbol<NoteEventType> {
    NOTE_CREATED, NOTE_UPDATED, NOTE_DELETED, NOTE_NOTIFICATION;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NoteEventType\",\"namespace\":\"com.squad.notebook.model\",\"symbols\":[\"NOTE_CREATED\",\"NOTE_UPDATED\",\"NOTE_DELETED\",\"NOTE_NOTIFICATION\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
