/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.squad.notebook.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class Notebook extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Notebook\",\"namespace\":\"com.squad.notebook.model\",\"fields\":[{\"name\":\"notebookId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"groupId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"noteId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"isPublic\",\"type\":\"boolean\"},{\"name\":\"NotebookType\",\"type\":{\"type\":\"enum\",\"name\":\"NotebookType\",\"symbols\":[\"NOTEBOOK\",\"GROUP_NOTEBOOK\"]}}]}");
  private static final long serialVersionUID = -3045044099064789169L;
  private static SpecificData MODEL$ = new SpecificData();
  private static final BinaryMessageEncoder<Notebook> ENCODER =
          new BinaryMessageEncoder<Notebook>(MODEL$ , SCHEMA$);
  private static final BinaryMessageDecoder<Notebook> DECODER =
          new BinaryMessageDecoder<Notebook>(MODEL$ , SCHEMA$);
  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Notebook>
          WRITER$ = (org.apache.avro.io.DatumWriter<Notebook>) MODEL$.createDatumWriter(SCHEMA$);
  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Notebook>
          READER$ = (org.apache.avro.io.DatumReader<Notebook>) MODEL$.createDatumReader(SCHEMA$);
  @Deprecated
  public java.lang.String notebookId;
  @Deprecated
  public java.lang.String userId;
  @Deprecated
  public java.lang.String groupId;
  @Deprecated
  public java.lang.String name;
  @Deprecated
  public java.lang.String noteId;
  @Deprecated
  public boolean isPublic;
  @Deprecated
  public com.squad.notebook.model.NotebookType NotebookType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Notebook() {
  }

  /**
   * All-args constructor.
   * @param notebookId The new value for notebookId
   * @param userId The new value for userId
   * @param groupId The new value for groupId
   * @param name The new value for name
   * @param noteId The new value for noteId
   * @param isPublic The new value for isPublic
   * @param NotebookType The new value for NotebookType
   */
  public Notebook(java.lang.String notebookId , java.lang.String userId , java.lang.String groupId , java.lang.String name , java.lang.String noteId , java.lang.Boolean isPublic , com.squad.notebook.model.NotebookType NotebookType) {
    this.notebookId = notebookId;
    this.userId = userId;
    this.groupId = groupId;
    this.name = name;
    this.noteId = noteId;
    this.isPublic = isPublic;
    this.NotebookType = NotebookType;
  }

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Notebook> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Notebook> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Notebook> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Notebook>(MODEL$ , SCHEMA$ , resolver);
  }

  /**
   * Deserializes a Notebook from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Notebook instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Notebook fromByteBuffer(
          java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /**
   * Creates a new Notebook RecordBuilder.
   * @return A new Notebook RecordBuilder
   */
  public static com.squad.notebook.model.Notebook.Builder newBuilder() {
    return new com.squad.notebook.model.Notebook.Builder();
  }

  /**
   * Creates a new Notebook RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Notebook RecordBuilder
   */
  public static com.squad.notebook.model.Notebook.Builder newBuilder(com.squad.notebook.model.Notebook.Builder other) {
    if (other == null) {
      return new com.squad.notebook.model.Notebook.Builder();
    } else {
      return new com.squad.notebook.model.Notebook.Builder(other);
    }
  }

  /**
   * Creates a new Notebook RecordBuilder by copying an existing Notebook instance.
   * @param other The existing instance to copy.
   * @return A new Notebook RecordBuilder
   */
  public static com.squad.notebook.model.Notebook.Builder newBuilder(com.squad.notebook.model.Notebook other) {
    if (other == null) {
      return new com.squad.notebook.model.Notebook.Builder();
    } else {
      return new com.squad.notebook.model.Notebook.Builder(other);
    }
  }

  /**
   * Serializes this Notebook to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return notebookId;
      case 1:
        return userId;
      case 2:
        return groupId;
      case 3:
        return name;
      case 4:
        return noteId;
      case 5:
        return isPublic;
      case 6:
        return NotebookType;
      default:
        throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$ , java.lang.Object value$) {
    switch (field$) {
      case 0:
        notebookId = (java.lang.String) value$;
        break;
      case 1:
        userId = (java.lang.String) value$;
        break;
      case 2:
        groupId = (java.lang.String) value$;
        break;
      case 3:
        name = (java.lang.String) value$;
        break;
      case 4:
        noteId = (java.lang.String) value$;
        break;
      case 5:
        isPublic = (java.lang.Boolean) value$;
        break;
      case 6:
        NotebookType = (com.squad.notebook.model.NotebookType) value$;
        break;
      default:
        throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'notebookId' field.
   * @return The value of the 'notebookId' field.
   */
  public java.lang.String getNotebookId() {
    return notebookId;
  }

  /**
   * Sets the value of the 'notebookId' field.
   * @param value the value to set.
   */
  public void setNotebookId(java.lang.String value) {
    this.notebookId = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'groupId' field.
   * @return The value of the 'groupId' field.
   */
  public java.lang.String getGroupId() {
    return groupId;
  }

  /**
   * Sets the value of the 'groupId' field.
   * @param value the value to set.
   */
  public void setGroupId(java.lang.String value) {
    this.groupId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'noteId' field.
   * @return The value of the 'noteId' field.
   */
  public java.lang.String getNoteId() {
    return noteId;
  }

  /**
   * Sets the value of the 'noteId' field.
   * @param value the value to set.
   */
  public void setNoteId(java.lang.String value) {
    this.noteId = value;
  }

  /**
   * Gets the value of the 'isPublic' field.
   * @return The value of the 'isPublic' field.
   */
  public boolean getIsPublic() {
    return isPublic;
  }

  /**
   * Sets the value of the 'isPublic' field.
   * @param value the value to set.
   */
  public void setIsPublic(boolean value) {
    this.isPublic = value;
  }

  /**
   * Gets the value of the 'NotebookType' field.
   * @return The value of the 'NotebookType' field.
   */
  public com.squad.notebook.model.NotebookType getNotebookType() {
    return NotebookType;
  }

  /**
   * Sets the value of the 'NotebookType' field.
   * @param value the value to set.
   */
  public void setNotebookType(com.squad.notebook.model.NotebookType value) {
    this.NotebookType = value;
  }

  @Override
  public void writeExternal(java.io.ObjectOutput out)
          throws java.io.IOException {
    WRITER$.write(this , SpecificData.getEncoder(out));
  }

  @Override
  public void readExternal(java.io.ObjectInput in)
          throws java.io.IOException {
    READER$.read(this , SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out)
          throws java.io.IOException {
    out.writeString(this.notebookId);

    out.writeString(this.userId);

    out.writeString(this.groupId);

    out.writeString(this.name);

    out.writeString(this.noteId);

    out.writeBoolean(this.isPublic);

    out.writeEnum(this.NotebookType.ordinal());

  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in)
          throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.notebookId = in.readString();

      this.userId = in.readString();

      this.groupId = in.readString();

      this.name = in.readString();

      this.noteId = in.readString();

      this.isPublic = in.readBoolean();

      this.NotebookType = com.squad.notebook.model.NotebookType.values()[in.readEnum()];

    } else {
      for (int i = 0 ; i < 7 ; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            this.notebookId = in.readString();
            break;

          case 1:
            this.userId = in.readString();
            break;

          case 2:
            this.groupId = in.readString();
            break;

          case 3:
            this.name = in.readString();
            break;

          case 4:
            this.noteId = in.readString();
            break;

          case 5:
            this.isPublic = in.readBoolean();
            break;

          case 6:
            this.NotebookType = com.squad.notebook.model.NotebookType.values()[in.readEnum()];
            break;

          default:
            throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  /**
   * RecordBuilder for Notebook instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Notebook>
          implements org.apache.avro.data.RecordBuilder<Notebook> {

    private java.lang.String notebookId;
    private java.lang.String userId;
    private java.lang.String groupId;
    private java.lang.String name;
    private java.lang.String noteId;
    private boolean isPublic;
    private com.squad.notebook.model.NotebookType NotebookType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.squad.notebook.model.Notebook.Builder other) {
      super(other);
      if (isValidValue(fields()[0] , other.notebookId)) {
        this.notebookId = data().deepCopy(fields()[0].schema() , other.notebookId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1] , other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema() , other.userId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2] , other.groupId)) {
        this.groupId = data().deepCopy(fields()[2].schema() , other.groupId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3] , other.name)) {
        this.name = data().deepCopy(fields()[3].schema() , other.name);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4] , other.noteId)) {
        this.noteId = data().deepCopy(fields()[4].schema() , other.noteId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5] , other.isPublic)) {
        this.isPublic = data().deepCopy(fields()[5].schema() , other.isPublic);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6] , other.NotebookType)) {
        this.NotebookType = data().deepCopy(fields()[6].schema() , other.NotebookType);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing Notebook instance
     * @param other The existing instance to copy.
     */
    private Builder(com.squad.notebook.model.Notebook other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0] , other.notebookId)) {
        this.notebookId = data().deepCopy(fields()[0].schema() , other.notebookId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1] , other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema() , other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2] , other.groupId)) {
        this.groupId = data().deepCopy(fields()[2].schema() , other.groupId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3] , other.name)) {
        this.name = data().deepCopy(fields()[3].schema() , other.name);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4] , other.noteId)) {
        this.noteId = data().deepCopy(fields()[4].schema() , other.noteId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5] , other.isPublic)) {
        this.isPublic = data().deepCopy(fields()[5].schema() , other.isPublic);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6] , other.NotebookType)) {
        this.NotebookType = data().deepCopy(fields()[6].schema() , other.NotebookType);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Gets the value of the 'notebookId' field.
     * @return The value.
     */
    public java.lang.String getNotebookId() {
      return notebookId;
    }


    /**
     * Sets the value of the 'notebookId' field.
     * @param value The value of 'notebookId'.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder setNotebookId(java.lang.String value) {
      validate(fields()[0] , value);
      this.notebookId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'notebookId' field has been set.
     * @return True if the 'notebookId' field has been set, false otherwise.
     */
    public boolean hasNotebookId() {
      return fieldSetFlags()[0];
    }


    /**
     * Clears the value of the 'notebookId' field.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder clearNotebookId() {
      notebookId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'userId' field.
     * @return The value.
     */
    public java.lang.String getUserId() {
      return userId;
    }


    /**
     * Sets the value of the 'userId' field.
     * @param value The value of 'userId'.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder setUserId(java.lang.String value) {
      validate(fields()[1] , value);
      this.userId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'userId' field has been set.
     * @return True if the 'userId' field has been set, false otherwise.
     */
    public boolean hasUserId() {
      return fieldSetFlags()[1];
    }


    /**
     * Clears the value of the 'userId' field.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'groupId' field.
     * @return The value.
     */
    public java.lang.String getGroupId() {
      return groupId;
    }


    /**
     * Sets the value of the 'groupId' field.
     * @param value The value of 'groupId'.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder setGroupId(java.lang.String value) {
      validate(fields()[2] , value);
      this.groupId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'groupId' field has been set.
     * @return True if the 'groupId' field has been set, false otherwise.
     */
    public boolean hasGroupId() {
      return fieldSetFlags()[2];
    }


    /**
     * Clears the value of the 'groupId' field.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder clearGroupId() {
      groupId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
     * Gets the value of the 'name' field.
     * @return The value.
     */
    public java.lang.String getName() {
      return name;
    }


    /**
     * Sets the value of the 'name' field.
     * @param value The value of 'name'.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder setName(java.lang.String value) {
      validate(fields()[3] , value);
      this.name = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
     * Checks whether the 'name' field has been set.
     * @return True if the 'name' field has been set, false otherwise.
     */
    public boolean hasName() {
      return fieldSetFlags()[3];
    }


    /**
     * Clears the value of the 'name' field.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder clearName() {
      name = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
     * Gets the value of the 'noteId' field.
     * @return The value.
     */
    public java.lang.String getNoteId() {
      return noteId;
    }


    /**
     * Sets the value of the 'noteId' field.
     * @param value The value of 'noteId'.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder setNoteId(java.lang.String value) {
      validate(fields()[4] , value);
      this.noteId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
     * Checks whether the 'noteId' field has been set.
     * @return True if the 'noteId' field has been set, false otherwise.
     */
    public boolean hasNoteId() {
      return fieldSetFlags()[4];
    }


    /**
     * Clears the value of the 'noteId' field.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder clearNoteId() {
      noteId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
     * Gets the value of the 'isPublic' field.
     * @return The value.
     */
    public boolean getIsPublic() {
      return isPublic;
    }


    /**
     * Sets the value of the 'isPublic' field.
     * @param value The value of 'isPublic'.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder setIsPublic(boolean value) {
      validate(fields()[5] , value);
      this.isPublic = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
     * Checks whether the 'isPublic' field has been set.
     * @return True if the 'isPublic' field has been set, false otherwise.
     */
    public boolean hasIsPublic() {
      return fieldSetFlags()[5];
    }


    /**
     * Clears the value of the 'isPublic' field.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder clearIsPublic() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
     * Gets the value of the 'NotebookType' field.
     * @return The value.
     */
    public com.squad.notebook.model.NotebookType getNotebookType() {
      return NotebookType;
    }


    /**
     * Sets the value of the 'NotebookType' field.
     * @param value The value of 'NotebookType'.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder setNotebookType(com.squad.notebook.model.NotebookType value) {
      validate(fields()[6] , value);
      this.NotebookType = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
     * Checks whether the 'NotebookType' field has been set.
     * @return True if the 'NotebookType' field has been set, false otherwise.
     */
    public boolean hasNotebookType() {
      return fieldSetFlags()[6];
    }


    /**
     * Clears the value of the 'NotebookType' field.
     * @return This builder.
     */
    public com.squad.notebook.model.Notebook.Builder clearNotebookType() {
      NotebookType = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Notebook build() {
      try {
        Notebook record = new Notebook();
        record.notebookId = fieldSetFlags()[0] ? this.notebookId : (java.lang.String) defaultValue(fields()[0]);
        record.userId = fieldSetFlags()[1] ? this.userId : (java.lang.String) defaultValue(fields()[1]);
        record.groupId = fieldSetFlags()[2] ? this.groupId : (java.lang.String) defaultValue(fields()[2]);
        record.name = fieldSetFlags()[3] ? this.name : (java.lang.String) defaultValue(fields()[3]);
        record.noteId = fieldSetFlags()[4] ? this.noteId : (java.lang.String) defaultValue(fields()[4]);
        record.isPublic = fieldSetFlags()[5] ? this.isPublic : (java.lang.Boolean) defaultValue(fields()[5]);
        record.NotebookType = fieldSetFlags()[6] ? this.NotebookType : (com.squad.notebook.model.NotebookType) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}










