/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.squad.notebook.model;

@org.apache.avro.specific.AvroGenerated
public enum NoteType implements org.apache.avro.generic.GenericEnumSymbol<NoteType> {
    NOTE, TASK;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NoteType\",\"namespace\":\"com.squad.notebook.model\",\"symbols\":[\"NOTE\",\"TASK\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
