/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.squad.notebook.model;

@org.apache.avro.specific.AvroGenerated
public enum NotebookType implements org.apache.avro.generic.GenericEnumSymbol<NotebookType> {
    NOTEBOOK, GROUP_NOTEBOOK;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NotebookType\",\"namespace\":\"com.squad.notebook.model\",\"symbols\":[\"NOTEBOOK\",\"GROUP_NOTEBOOK\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
