/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.squad.post.model;
@org.apache.avro.specific.AvroGenerated
public enum PostEventType implements org.apache.avro.generic.GenericEnumSymbol<PostEventType> {
  POST_CREATED, POST_UPDATED, POST_LIKED, POST_UNLIKED, POST_DELETED, POST_NOTIFICATION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PostEventType\",\"namespace\":\"com.squad.post.model\",\"symbols\":[\"POST_CREATED\",\"POST_UPDATED\",\"POST_LIKED\",\"POST_UNLIKED\",\"POST_DELETED\",\"POST_NOTIFICATION\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
