/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.squad.chat.model;
@org.apache.avro.specific.AvroGenerated
public enum ChatroomEventType implements org.apache.avro.generic.GenericEnumSymbol<ChatroomEventType> {
  CHATROOM_CREATED, CHATROOM_UPDATED, CHATROOM_USER_ADDED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ChatroomEventType\",\"namespace\":\"com.squad.chat.model\",\"symbols\":[\"CHATROOM_CREATED\",\"CHATROOM_UPDATED\",\"CHATROOM_USER_ADDED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
