/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.squad.chat.model;
@org.apache.avro.specific.AvroGenerated
public enum MessageEventType implements org.apache.avro.generic.GenericEnumSymbol<MessageEventType> {
  MESSAGE_SEND, MESSAGE_NOFITICATION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MessageEventType\",\"namespace\":\"com.squad.chat.model\",\"symbols\":[\"MESSAGE_SEND\",\"MESSAGE_NOFITICATION\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
